[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.up.railway.app/api"
  REACT_APP_CONTACT_EMAIL = "duraikannan73@gmail.com"
  REACT_APP_CONTACT_PHONE_1 = "+91 7338031038"
  REACT_APP_CONTACT_PHONE_2 = "+91 9980667425"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-url.up.railway.app/api"
  REACT_APP_CONTACT_EMAIL = "duraikannan73@gmail.com"
  REACT_APP_CONTACT_PHONE_1 = "+91 7338031038"
  REACT_APP_CONTACT_PHONE_2 = "+91 9980667425"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-backend-url.up.railway.app/api"
  REACT_APP_CONTACT_EMAIL = "duraikannan73@gmail.com"
  REACT_APP_CONTACT_PHONE_1 = "+91 7338031038"
  REACT_APP_CONTACT_PHONE_2 = "+91 9980667425"